BaseURL = "http://potofjoy.com/comic/"
title = "The Maid of Orléans"
languageCode = "en-us"
theme = "slim"

[params]
  Subtitle = "A medieval adventure tale"
  # GithubID = "Your Github ID"
  # TwitterID = "Your Twitter ID"
  # AnalyticsID = "Your Google Analytics tracking code"
  # DisqusShortname = "Your Disqus shortname"
  Summary = false  # takes true or false
  Content = false  # takes true or false
  # if both are set to true, summary is shown.
  # FooterMsg = "Copyright Me 2016. Powered by Hugo."
